version: "3"

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME={DB_USERNAME}
      - POSTGRESQL_PASSWORD={DB_PASSWORD}
      - POSTGRESQL_DATABSE={DB_TABLE}